Core_Veterinaria/Core_Veterinaria/Models/ApplicationDbContext.cs
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Core_Veterinaria.Models
{
    public class ApplicationDbContext : DbContext 
    {
        public ApplicationDbContext(DbContextOptions<ApplicationDbContext> options) : base(options)
        {
        }
        public DbSet<Perro> Perros { get; set; } 
        //<Entity> y el nombre debe ser el nombre de la tabla DB
    }
}

Core_Veterinaria/Core_Veterinaria/Models/ErrorViewModel.cs
using System;

namespace Core_Veterinaria.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Core_Veterinaria/Core_Veterinaria/Models/Perro.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Core_Veterinaria.Models
{
    public class Perro
    {
        [Key]
        public int P_id { get; set; }

        [Required(ErrorMessage = "Ingresa el nombre del perro")]
        [Display(Name ="Nombre del perro")]
        public string Nombre { get; set; }

        [Required(ErrorMessage = "Ingresa la raza")]
        [Display(Name ="Raza")]
        public string Raza { get; set; }

        [Required(ErrorMessage = "Ingresa la vacuna")]
        [Display(Name = "Vacuna")]
        public string Vacunas { get; set; }

        [Required(ErrorMessage = "Ingresa el sexo")]
        [Display(Name = "Sexo")]
        public string Sexo { get; set; }

        [Required(ErrorMessage = "Ingresa la edad")]
        [Display(Name = "Edad")]
        [Range(1, 22)]
        public int Edad { get; set; }


    }
}

Core_Veterinaria/Core_Veterinaria/Controllers/PerroController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Core_Veterinaria.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Core_Veterinaria.Controllers
{
    public class PerroController : Controller
    {
        private readonly ApplicationDbContext _db;

        public PerroController(ApplicationDbContext db)
        {
            _db = db;
        }

        public IActionResult Index()
        {
            var displaydata = _db.Perros.ToList();
            return View(displaydata);
        }

        [HttpGet]
        public async Task<IActionResult> Index(string perroSearch)
        {
            ViewData["GetPerroDetails"] = perroSearch;
            var perroquery = from x in _db.Perros select x;
            if (!String.IsNullOrEmpty(perroSearch))
            {
                perroquery = perroquery.Where(x => x.Nombre.Contains(perroSearch)||
                x.Raza.Contains(perroSearch));
            }
            return View(await perroquery.AsNoTracking().ToListAsync());

        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(Perro nPerro)
        {
            if (ModelState.IsValid)
            {
                _db.Add(nPerro);
                await _db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(nPerro);
        }

        public async Task<IActionResult> Detail(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Index)");
            }
            var getPerroDetail = await _db.Perros.FindAsync(id);
            return View(getPerroDetail);
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Index)");
            }

            var getPerroDetail = await _db.Perros.FindAsync(id);
            return View(getPerroDetail);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(Perro oldPerro)
        {
            if (ModelState.IsValid)
            {
                _db.Update(oldPerro);
                await _db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(oldPerro);
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Index)");
            }

            var getPerroDetail = await _db.Perros.FindAsync(id);
            return View(getPerroDetail);
        }
         
        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            var getPerrodetail = await _db.Perros.FindAsync(id);
            _db.Perros.Remove(getPerrodetail);
            await _db.SaveChangesAsync();
            return RedirectToAction("Index");
        }
    }
}

Core_Veterinaria/Core_Veterinaria/Views/Perro/Create.cshtml
@model Core_Veterinaria.Models.Perro

@{
    ViewData["Title"] = "Create";
}

<h1>Agregar nuevo perro</h1>

<h4>Perro</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Raza" class="control-label"></label>
                <input asp-for="Raza" class="form-control" />
                <span asp-validation-for="Raza" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Vacunas" class="control-label"></label>
                <input asp-for="Vacunas" class="form-control" />
                <span asp-validation-for="Vacunas" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Sexo" class="control-label"></label>
                <input asp-for="Sexo" class="form-control" />
                <span asp-validation-for="Sexo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Edad" class="control-label"></label>
                <input asp-for="Edad" class="form-control" />
                <span asp-validation-for="Edad" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Core_Veterinaria/Core_Veterinaria/Views/Perro/Delete.cshtml
@model Core_Veterinaria.Models.Perro

@{
    ViewData["Title"] = "Delete";
}

<h1>Eliminar Perro :v</h1>

<h3>¿Desea borrar los datos del perro?</h3>
<div>
    <h4>Perro</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.P_id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.P_id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nombre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Raza)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Raza)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Vacunas)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Vacunas)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Sexo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Sexo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Edad)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Edad)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Core_Veterinaria/Core_Veterinaria/Views/Perro/Detail.cshtml
@model Core_Veterinaria.Models.Perro

@{
    ViewData["Title"] = "Detail";
}

<h1>Detalle Perro</h1>

<div>
    <h4>Datos: </h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.P_id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.P_id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nombre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Raza)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Raza)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Vacunas)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Vacunas)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Sexo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Sexo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Edad)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Edad)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new {id = Model.P_id})|
    <a asp-action="Index">Back to List</a>
</div>

Core_Veterinaria/Core_Veterinaria/Views/Perro/Edit.cshtml
@model Core_Veterinaria.Models.Perro

@{
    ViewData["Title"] = "Edit";
}

<h1>Actualizar</h1>

<h4>Perro</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="P_id" class="control-label"></label>
                <input asp-for="P_id" class="form-control" readonly />
                <span asp-validation-for="P_id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Raza" class="control-label"></label>
                <input asp-for="Raza" class="form-control" />
                <span asp-validation-for="Raza" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Vacunas" class="control-label"></label>
                <input asp-for="Vacunas" class="form-control" />
                <span asp-validation-for="Vacunas" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Sexo" class="control-label"></label>
                <input asp-for="Sexo" class="form-control" />
                <span asp-validation-for="Sexo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Edad" class="control-label"></label>
                <input asp-for="Edad" class="form-control" />
                <span asp-validation-for="Edad" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Core_Veterinaria/Core_Veterinaria/Views/Perro/Index.cshtml
@model IEnumerable<Core_Veterinaria.Models.Perro>

@{
    ViewData["Title"] = "Index";
}

<h1>Lista de perros</h1>

<p>
    <a asp-action="Create">Ingresa nuevo perro</a>
</p>

<form asp-action="Index" method="get">
    <p>
        <i class="fade fa-search"></i>
        <input type="search" placeholder="Ingresa nombre ó raza" name="perroSearch"
               value="@ViewData["GetPerroDetails"]" style="width:500px;" />
        <input type="submit" value="Buscar" class="btn btn-primary" />
        <a asp-action="Index">Ver todos</a>
    </p>
</form>



<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.P_id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nombre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Raza)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Vacunas)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Sexo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Edad)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.P_id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nombre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Raza)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Vacunas)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Sexo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Edad)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id=item.P_id},new { @class = "btn btn-primary" })|
                @Html.ActionLink("Details", "Detail", new {id=item.P_id},new { @class = "btn btn-success" })|
                @Html.ActionLink("Delete", "Delete", new { id=item.P_id},new { @class = "btn btn-danger" })
            </td>
        </tr>
}
    </tbody>
</table>

Core_Veterinaria/Core_Veterinaria/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Core_Veterinaria</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Perro" asp-action="Index">Core_Veterinaria</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Perro" asp-action="Index">Home</a>
                        </li>
                        
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Core_Veterinaria 
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>